Use Jupyterlab3/Federated Extension System
glue-viz/bqplot-image-gl pull request #35
Opened 2020-11-04 12:58 UTC by maartenbreddels

This avoids users having to build/use nodejs for JLab3

2020-11-05 15:04 UTC, maartenbreddels commented
@astrofrog could you take a look at this, the failure is because for some reason the pyproject.toml is not respected, it should install jupyter lab which is not part of the build process.

2020-11-10 22:44 UTC, astrofrog commented
Yes will look shortly!

2020-11-11 09:17 UTC, astrofrog commented
@maartenbreddels - I think the CI should be fixed now.

2020-11-11 09:19 UTC, astrofrog commented
I also removed your workaround commit

2020-11-11 10:17 UTC, astrofrog commented
Not sure what is going on with the coverage but I think we can ignore for now

2021-02-10 10:31 UTC, maartenbreddels commented
@astrofrog the last two commits I don't understand:
 * ci: add setup.py to manifest, unclear why
 * ci: jupyter_packaging everywhere
 
I don't think they should be there, could you take a look?

2021-02-10 20:08 UTC, astrofrog commented
Will take a look tomorrow morning!

2021-02-11 10:56 UTC, astrofrog commented
@maartenbreddels - there were two separate issues:

* I think sdist is buggy in jupyter-packaging: https://github.com/jupyter/jupyter-packaging/pull/66 (I added a workaround here for now)
* There was a typo in the jupyter-packaging name in ``pyproject.toml``

Does this make sense?

2021-02-11 11:10 UTC, astrofrog commented
Investigating a follow-up issue, think it should be fixable

2021-02-11 11:35 UTC, maartenbreddels commented
Great, feel free to squash some commits if that cleans it up.

2021-02-11 12:01 UTC, astrofrog approved these changes
Looks good to me now! I think the setup.py could be simplified further as there is still some commented code.

2021-02-11 13:23 UTC, astrofrog commented
Wait actually I think they just released a version of jupyter-packaging with the fox so I think we can remove the workaround and update the min pinned version in pyproject, will push a commit shortly

2021-02-12 09:05 UTC, astrofrog requested changes
A few small things then I think this can be merged and released - thanks @maartenbreddels !

2021-02-12 09:05 UTC, astrofrog commented on pyproject.toml
> +requires = ["jupyter-packaging~=0.7.9",
Change to 0.7.12

2021-02-12 09:05 UTC, astrofrog commented on setup.py
> +#     ]
Remove?

2021-02-12 09:05 UTC, astrofrog commented on setup.py
> +#     build_py.finalize_options()
Remove?

2021-02-12 09:05 UTC, astrofrog commented on setup.py
> +# Adding "map_data" as package_data manually, this should not be needed because it's already
Is this comment still relevant?

2021-02-12 09:05 UTC, astrofrog commented on setup.py
> +cmdclass['sdist'] = _wrap_command(['jsdeps'], sdist, strict=True)
This workaround can be removed with jupyter packaging 0.7.12

2021-02-12 11:01 UTC, merged